---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-6.0.10
  - name: debian-7.6

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
